---

- hosts: mac
  gather_facts: no
  tasks:
  - include: tasks/always.yaml
    tags: always

  - name: "Tap a Homebrew caskroom/versions repository"
    homebrew_tap:
      name: "caskroom/versions"

- name: "Configure Mac OS X, install Dev & Ops tools"
  hosts: mac
  gather_facts: no
  tasks:
  - name: install tools
    homebrew: name="{{item}}" state={{ pkg_state }}
    with_items:
    - ansible
    - bash-completion
    - git
    - libvirt
    - nmap
    - ssh-copy-id
    - tmux
    - tree
    - wget
    - curl
    - xhyve
    - qemu
    - zmq
    - node
    - python
    - go
    - pv
    - iperf3
    - packer # Hashicorp / Vagrant Tool for creating identical machine images for multiple platforms
    - autoconf
    - pkg-config
    - azure-cli
    - p7zip
    - android-platform-tools

  - name: install nice applications
    homebrew_cask: name="{{item}}" state="present"
    with_items:
    - skype
    - google-chrome
    - google-chrome-canary
    - firefox
    - firefoxnightly
    - vlc
    - spotify
    - virtualbox
    - xca
    - vagrant
    - docker-toolbox
    - atom
    - bonjour-browser
    - the-unarchiver
    - xquartz # Required t build virt-manager
    - minikube
    - helm

  - name: "Install pip modules"
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
    - enum # for any reason is required by ipython and not installed o0
    - ipython

  - include: tasks/mac_preferences.yaml
  - include: tasks/atom.yaml
  - include: tasks/gcloud.yaml

  # Required by minikube if VM drive is xhyve
  - include: tasks/docker-machine-driver-xhyve.yaml

# vi:ft=ansible
