---

- hosts: mac
  gather_facts: no
  tasks:
  - include: tasks/always.yaml
    tags: always
    when: "'personal' in group_names"

  - name: "Tap a Homebrew caskroom/versions repository"
    homebrew_tap:
      name: "caskroom/versions"

- name: "Configure Mac OS X, install Dev & Ops tools"
  hosts: mac
  gather_facts: no
  handlers:
  # Apply Dock settings
  - name: Reload OS X Dock
    command: "launchctl stop com.apple.Dock.agent"

  - name: Reload Finder
    command: "killall Finder"

  tasks:
  - name: "Update homebrew and upgrade all packages"
    homebrew: update_homebrew=yes upgrade_all=yes
    tags: [ brew ]

  - name: "Configure static hosts"
    become: yes
    lineinfile:
      path: /etc/hosts
      regexp: "^{{ item | regex_escape() }}$"
      line: "{{ item }}"
    with_items: "{{ static_hosts }}"
    tags: [ hosts ]

  - name: install tools
    homebrew: name="{{item}}" state={{ pkg_state }} update_homebrew=Yes
    with_items: "{{ brew_packages }}"
    tags: [ brew ]

  - name: install nice applications
    homebrew_cask: name="{{item}}" state="present" update_homebrew=Yes
    with_items: "{{ brew_cask_packages }}"
    tags: [ brew, cask ]

  - name: "Remove old brew packages"
    homebrew: name="{{item}}" state="absent"
    with_items: []
    tags: [ cleanup ]

  - name: "Homebrew cleanup"
    command: "brew cleanup"
    tags: [ brew, cleanup ]

  - name: "Install pip modules"
    pip:
      name: "{{ item }}"
      state: latest
    with_items: "{{ pip_packages }}"
    tags: [ pip, python ]

  # TODO: this is not working, is not installing binaries o0
  - name: "Install Ruby modules"
    gem:
      name: "{{ item }}"
      state: latest
    with_items: "{{ gem_packages }}"
    tags: [ gems, ruby ]

  - include: tasks/mac_preferences.yaml
    tags: [ osx, preferences ]
  - include: tasks/atom.yaml
    tags: [ atom ]
  - include: tasks/gcloud.yaml
    when: "'personal' in group_names"

  # Required by minikube if VM drive is xhyve
  - include: tasks/docker-machine-driver-xhyve.yaml
    when: "'personal' in group_names"

  # TODO: this is not working, is not installing binaries o0
  - name: "Install VSCode extensions"
    shell: "code --install-extension {{ item }}"
    with_items: "{{ vscode_packages }}"
    tags: [ vscode ]

  - include: tasks/mac_pam_yubikey.yaml
    become: yes
    tags: [ yubikey ]

- name: ""
  hosts: mac
  gather_facts: yes
  vars:
    tlds:
      localhost:
        address:
          - 127.0.0.1
      dev:
        address:
          - 127.0.0.1
      cpp.nonlive:
        server:
          - 192.168.88.4
          - 192.168.88.5
  roles:
    - name: "Configure DNSmasq"
      role: dnsmasq
      tags: dns
      when: "'al' in group_names"

# vi:ft=ansible
