---

- hosts: mac
  gather_facts: no
  tasks:
  - include: tasks/always.yaml
    tags: always
    when: "'personal' in group_names"

  - name: "Tap a Homebrew caskroom/versions repository"
    homebrew_tap:
      name: "caskroom/versions"
    when: "'personal' in group_names"

- name: "Configure Mac OS X, install Dev & Ops tools"
  hosts: mac
  gather_facts: no
  handlers:
  # Apply Dock settings
  - name: Reload OS X Dock
    command: "launchctl stop com.apple.Dock.agent"

  tasks:
  - name: "Update homebrew and upgrade all packages"
    homebrew: update_homebrew=yes upgrade_all=yes
    tags: [ brew ]

  - name: install tools
    homebrew: name="{{item}}" state={{ pkg_state }} update_homebrew=Yes
    with_items: "{{ packages.brew }}"
    tags: [ brew ]

  - name: install nice applications
    homebrew_cask: name="{{item}}" state="present" update_homebrew=Yes
    with_items: "{{ packages.brew_cask }}"
    tags: [ brew, cask ]

  - name: "Remove old brew packages"
    homebrew_cask: name="{{item}}" state="absent"
    with_items:
    - ansible
    tags: [ cleanup ]

  - name: "Install pip modules"
    pip:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages.pip }}"
    tags: [ pip, python ]

  - include: tasks/mac_preferences.yaml
    tags: [ osx, preferences ]
  - include: tasks/atom.yaml
    tags: [ atom ]
  - include: tasks/gcloud.yaml
    when: "'personal' in group_names"

  # Required by minikube if VM drive is xhyve
  - include: tasks/docker-machine-driver-xhyve.yaml
    when: "'personal' in group_names"

# vi:ft=ansible
