---

- hosts: mac
  gather_facts: no
  tasks:
  - include: tasks/always.yaml
    tags: always
    when: "'personal' in group_names"

  - name: "Tap a Homebrew caskroom/versions repository"
    homebrew_tap:
      name: "caskroom/versions"

- name: "Configure Mac OS X, install Dev & Ops tools"
  hosts: mac
  gather_facts: no
  handlers:
  # Apply Dock settings
  - name: Reload OS X Dock
    command: "launchctl stop com.apple.Dock.agent"

  - name: Reload Finder
    command: "killall Finder"

  tasks:
  - name: "Update homebrew and upgrade all packages"
    homebrew: update_homebrew=yes upgrade_all=yes
    tags: [ brew ]

  - name: "Configure static hosts"
    become: yes
    lineinfile:
      path: /etc/hosts
      regexp: "^{{ item | regex_escape() }}$"
      line: "{{ item }}"
    with_items: "{{ all_static_hosts + ( static_hosts if static_hosts is defined else [] ) }}"
    tags: [ hosts ]

  - name: install tools
    homebrew: name="{{item}}" state={{ pkg_state }} update_homebrew=Yes
    with_items: "{{ all_packages.brew + ( packages.brew if 'brew' in packages else [] ) }}"
    tags: [ brew ]

  - name: install nice applications
    homebrew_cask: name="{{item}}" state="present" update_homebrew=Yes
    with_items: "{{ all_packages.brew_cask + ( packages.brew_cask if 'brew_cask' in packages else [] ) }}"
    tags: [ brew, cask ]

  - name: "Remove old brew packages"
    homebrew_cask: name="{{item}}" state="absent"
    with_items:
    - ansible
    tags: [ cleanup ]

  - name: "Homebrew cleanup"
    command: "brew cleanup"
    tags: [ brew, cleanup ]

  - name: "Install pip modules"
    pip:
      name: "{{ item }}"
      state: latest
    with_items: "{{ all_packages.pip + ( packages.pip if 'pip' in packages else [] ) }}"
    tags: [ pip, python ]

  - include: tasks/mac_preferences.yaml
    tags: [ osx, preferences ]
  - include: tasks/atom.yaml
    tags: [ atom ]
  - include: tasks/gcloud.yaml
    when: "'personal' in group_names"

  # Required by minikube if VM drive is xhyve
  - include: tasks/docker-machine-driver-xhyve.yaml
    when: "'personal' in group_names"

  # https://github.com/Homebrew/homebrew-core/pull/14408
  - name: "Fix python"
    file:
      src: "../Cellar/python/2.7.13_1/bin/python2"
      dest: "/usr/local/bin/python"
      state: link
    tags: here

# vi:ft=ansible
