---

- hosts: mac
  gather_facts: no
  tasks:
  - include: tasks/always.yaml
    tags: always
    when: "'personal' in group_names"

  - name: "Add taps to Homebrew"
    homebrew_tap:
      name: "{{ item }}"
    when: false
    with_items: "{{ brew_taps }}"
    tags: [ brew ]

- name: "Configure Mac OS X, install Dev & Ops tools"
  hosts: mac
  gather_facts: no
  handlers:
  # Apply Dock settings
  - name: Reload OS X Dock
    command: "launchctl stop com.apple.Dock.agent"

  - name: Reload Finder
    command: "killall Finder"

  tasks:
  - name: "Update homebrew and upgrade all packages"
    homebrew: update_homebrew=yes upgrade_all=yes
    tags: [ brew ]

  - name: "Configure static hosts"
    become: yes
    lineinfile:
      path: /etc/hosts
      regexp: "^{{ item | regex_escape() }}$"
      line: "{{ item }}"
    with_items: "{{ static_hosts }}"
    tags: [ hosts ]

  - name: install tools
    homebrew:
      name: "{{ brew_packages }}"
      state: "{{ pkg_state }}"
      update_homebrew: Yes
    tags: [ brew ]

  - name: install nice applications
    homebrew_cask:
      name: "{{ brew_cask_packages }}"
      state: "{{ pkg_state }}"
      update_homebrew: Yes
    tags: [ brew, cask ]

  - name: "Remove old brew packages"
    homebrew: name="{{item}}" state="absent"
    with_items: "{{ brew_cleanup_packages }}"
    tags: [ cleanup ]

  - name: "Homebrew cleanup"
    command: "brew cleanup"
    register: brew_cleanup
    changed_when: "brew_cleanup.stdout_lines | length > 0"
    tags: [ brew, cleanup ]

  - name: "Install pip modules"
    pip:
      name: "{{ pip_packages }}"
      state: "{{ pkg_state }}"
    tags: [ pip, python ]

  # TODO: this is not working, is not installing binaries o0
  - name: "Install Ruby modules"
    gem:
      name: "{{ item }}"
      state: "{{ pkg_state }}"
    with_items: "{{ gem_packages }}"
    tags: [ gems, ruby ]

  - include: tasks/mac_preferences.yaml
    tags: [ osx, preferences ]
  - include: tasks/gcloud.yaml
    when: "'personal' in group_names"

  # Required by minikube if VM drive is xhyve
  - include: tasks/docker-machine-driver-xhyve.yaml
    when: "'personal' in group_names"

  # TODO: this is not working, is not installing binaries o0
  - name: "Install VSCode extensions"
    shell: "code --install-extension {{ item }}"
    with_items: "{{ vscode_packages }}"
    tags: [ vscode ]

  - include: tasks/mac_pam_yubikey.yaml
    become: yes
    tags: [ yubikey , never]

# vi:ft=ansible
