- name: Get brew prefix
  command: brew --prefix
  register: brew_prefix
  changed_when: False
  check_mode: no

- name: Set brew prefix fact
  set_fact:
    brew_prefix: "{{ brew_prefix.stdout }}"

# vi:ft=ansible
