---

- name: install tools
  homebrew: name="{{item}}" state={{ pkg_state }} # update_homebrew=Yes
  with_items:
  - docker-machine-driver-xhyve

- name: "Fix docker machine xhyve driver permissions"
  become: True
  file:
    # Follow file link, if not followed we need to deal with path that contains
    # a the driver version.
    path: "{{ brew_prefix }}/bin/docker-machine-driver-xhyve"
    follow: True
    owner: root
    group: wheel
    mode: u+s
    state: file
