---
# Info
# * https://www.yubico.com/wp-content/uploads/2016/02/Yubico_YubiKeyMacOSXLogin_en.pdf

- name: Require Yubikey to exit screensaver
  pamd:
    name: screensaver
    backup: Yes
    type: account
    control: required
    module_path: "pam_opendirectory.so"
    new_type: auth
    new_control: required
    new_module_path: "/usr/local/lib/security/pam_yubico.so"
    module_arguments:
      - "mode=challenge-response"
    state: before

- name: Require Yubikey to OS X login
  pamd:
    name: authorization
    backup: Yes
    type: account
    control: required
    module_path: "pam_opendirectory.so"
    new_type: auth
    new_control: required
    new_module_path: "/usr/local/lib/security/pam_yubico.so"
    module_arguments:
      - "mode=challenge-response"
    state: before

- name: Require Yubikey to login
  pamd:
    name: login
    backup: Yes
    type: account
    control: required
    module_path: "pam_nologin.so"
    new_type: auth
    new_control: required
    new_module_path: "/usr/local/lib/security/pam_yubico.so"
    module_arguments:
      - "mode=challenge-response"
    state: before

- name: Require Yubikey to sudo
  pamd:
    name: sudo
    backup: Yes
    type: account
    control: required
    module_path: "pam_opendirectory.so"
    new_type: auth
    new_control: required
    new_module_path: "/usr/local/lib/security/pam_yubico.so"
    module_arguments:
      - "mode=challenge-response"
    state: before
